version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  # The Windows orb give you everything you need to start using the Windows executor.
  win: circleci/windows@2.2.0 

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout

      - run:
          name: get JUCE latest
          command: git clone https://github.com/WeAreROLI/JUCE.git

      - run:
          command: .\build_vs2019.bat
          shell: powershell.exe

      - store_artifacts:
          path: /bin